### ISSUE TITLE
Git based audit:code breaks occasionally when showing diffs

### ISSUE THREAD

**Issue by timgentry** [PublicHealthEngland/ndr_dev_support#12]
When running `rake audit:code max_print=-1 show_diffs=true` within a git clone of https://github.com/PublicHealthEngland/ndr_ui we get errors like

```
fatal: Invalid revision range 3b818a19dd75d1b7810657ba0bdd11572a51d649..3b818a19dd75d1b7810657ba0ddd11572a51d649
```

**Comment by timgentry** [comment]
@bpellegr is this fixed as part of your recent PR?

**Comment by bpellegr** [comment]
Yes, all fixed code_safety.yml had some invalid entries

**Comment by timgentry** [comment]
Thanks @bpellegr
