### ISSUE TITLE
NdrDevSupport::Daemon::Stoppable uses the Rails.logger

### ISSUE THREAD

**Issue by timgentry** [PublicHealthEngland/ndr_dev_support#29]
NdrDevSupport::Daemon::Stoppable uses the Rails.logger and therefore can't work outside the Rails environment. Should we add the following to `Stoppable` or add a `Loggable` concern?

```ruby
attribute_write :logger

def logger
  @logger ||= defined?(Rails) ? Rails.logger : Logger.new(STDOUT)
end
```

**Comment by timgentry** [comment]
cc @joshpencheon

**Comment by joshpencheon** [comment]
Yep I think that's fine to add directly. I would say generally to use `$stdout` rather than `STDOUT` though, as the former can be redirected if needed.

I notice it also references `Rails.env.test?`; I think that whole line can just be deleted in favour of logging just to the `logger`.

**Comment by timgentry** [comment]
Being able to log to somewhere other than the Rails log or `$stdout` is becoming more urgent.
