### ISSUE TITLE
Switch from chromedriver-helper to webdrivers

### ISSUE THREAD

**Issue by timgentry** [PublicHealthEngland/ndr_dev_support#53]
`chromedriver-helper` is deprecated after 2019-03-31 and we should switch to `webdrivers`. See https://github.com/flavorjones/chromedriver-helper/issues/83

**Comment by joshpencheon** [comment]
Just came to open this raise this issue myself! Rails' own PR to handle the switch is here: https://github.com/rails/rails/pull/35732/files
