### ISSUE TITLE
Change Layout/AlignHash to table mode

### ISSUE THREAD

**Issue by drewthorp** [PublicHealthEngland/ndr_dev_support#61]
As a developer I wish the Rubocop setting for the Layout/AlignHash cop to be table mode.
Because at present it uses the default (No alignment) and this does not fall in line with the best practice as agreed with the NDR technical architect.
* It's done when the following does not report a Rubocop error :
```
  hash = {
    a_key:       1,
    another_key: 2
  }
```

**Comment by timgentry** [comment]
I hate table mode

**Comment by timgentry** [comment]
Hate it

**Comment by timgentry** [comment]
👍
